// Auto-generated by scripts/generate-m-plus-font-files.ts
// Do not edit manually.
// biome-ignore-all assist/source/organizeImports: generated file

// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_0_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-0-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_1_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-1-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_10_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-10-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_100_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-100-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_101_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-101-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_102_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-102-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_103_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-103-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_104_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-104-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_105_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-105-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_106_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-106-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_107_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-107-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_108_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-108-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_109_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-109-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_11_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-11-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_110_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-110-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_111_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-111-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_112_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-112-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_113_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-113-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_114_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-114-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_115_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-115-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_116_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-116-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_117_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-117-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_118_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-118-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_119_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-119-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_12_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-12-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_13_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-13-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_14_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-14-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_15_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-15-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_16_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-16-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_17_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-17-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_18_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-18-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_19_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-19-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_20_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-20-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_21_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-21-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_22_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-22-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_23_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-23-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_24_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-24-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_25_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-25-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_26_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-26-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_27_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-27-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_28_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-28-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_29_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-29-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_3_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-3-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_30_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-30-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_31_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-31-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_32_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-32-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_33_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-33-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_34_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-34-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_35_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-35-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_36_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-36-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_37_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-37-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_38_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-38-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_39_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-39-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_40_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-40-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_41_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-41-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_42_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-42-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_43_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-43-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_44_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-44-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_45_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-45-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_46_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-46-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_47_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-47-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_48_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-48-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_49_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-49-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_5_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-5-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_50_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-50-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_53_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-53-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_54_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-54-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_55_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-55-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_56_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-56-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_58_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-58-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_59_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-59-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_6_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-6-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_60_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-60-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_61_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-61-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_62_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-62-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_63_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-63-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_64_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-64-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_65_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-65-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_66_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-66-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_67_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-67-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_68_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-68-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_69_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-69-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_7_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-7-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_70_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-70-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_71_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-71-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_72_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-72-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_73_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-73-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_74_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-74-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_75_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-75-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_76_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-76-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_77_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-77-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_78_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-78-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_79_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-79-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_8_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-8-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_80_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-80-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_81_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-81-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_82_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-82-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_83_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-83-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_84_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-84-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_85_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-85-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_86_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-86-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_87_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-87-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_88_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-88-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_89_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-89-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_9_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-9-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_90_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-90-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_91_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-91-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_92_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-92-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_93_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-93-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_94_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-94-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_95_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-95-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_96_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-96-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_97_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-97-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_98_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-98-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_99_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-99-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_latin_ext_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-latin-ext-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_latin_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-latin-wght-normal.woff2" with {
  type: "file",
};
// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time
import mPlus_m_plus_1_code_vietnamese_wght_normal_woff2 from "@fontsource-variable/m-plus-1-code/files/m-plus-1-code-vietnamese-wght-normal.woff2" with {
  type: "file",
};

export const mPlusFontFiles = new Map<string, string>([
  ["m-plus-1-code-0-wght-normal.woff2", mPlus_m_plus_1_code_0_wght_normal_woff2],
  ["m-plus-1-code-1-wght-normal.woff2", mPlus_m_plus_1_code_1_wght_normal_woff2],
  ["m-plus-1-code-10-wght-normal.woff2", mPlus_m_plus_1_code_10_wght_normal_woff2],
  ["m-plus-1-code-100-wght-normal.woff2", mPlus_m_plus_1_code_100_wght_normal_woff2],
  ["m-plus-1-code-101-wght-normal.woff2", mPlus_m_plus_1_code_101_wght_normal_woff2],
  ["m-plus-1-code-102-wght-normal.woff2", mPlus_m_plus_1_code_102_wght_normal_woff2],
  ["m-plus-1-code-103-wght-normal.woff2", mPlus_m_plus_1_code_103_wght_normal_woff2],
  ["m-plus-1-code-104-wght-normal.woff2", mPlus_m_plus_1_code_104_wght_normal_woff2],
  ["m-plus-1-code-105-wght-normal.woff2", mPlus_m_plus_1_code_105_wght_normal_woff2],
  ["m-plus-1-code-106-wght-normal.woff2", mPlus_m_plus_1_code_106_wght_normal_woff2],
  ["m-plus-1-code-107-wght-normal.woff2", mPlus_m_plus_1_code_107_wght_normal_woff2],
  ["m-plus-1-code-108-wght-normal.woff2", mPlus_m_plus_1_code_108_wght_normal_woff2],
  ["m-plus-1-code-109-wght-normal.woff2", mPlus_m_plus_1_code_109_wght_normal_woff2],
  ["m-plus-1-code-11-wght-normal.woff2", mPlus_m_plus_1_code_11_wght_normal_woff2],
  ["m-plus-1-code-110-wght-normal.woff2", mPlus_m_plus_1_code_110_wght_normal_woff2],
  ["m-plus-1-code-111-wght-normal.woff2", mPlus_m_plus_1_code_111_wght_normal_woff2],
  ["m-plus-1-code-112-wght-normal.woff2", mPlus_m_plus_1_code_112_wght_normal_woff2],
  ["m-plus-1-code-113-wght-normal.woff2", mPlus_m_plus_1_code_113_wght_normal_woff2],
  ["m-plus-1-code-114-wght-normal.woff2", mPlus_m_plus_1_code_114_wght_normal_woff2],
  ["m-plus-1-code-115-wght-normal.woff2", mPlus_m_plus_1_code_115_wght_normal_woff2],
  ["m-plus-1-code-116-wght-normal.woff2", mPlus_m_plus_1_code_116_wght_normal_woff2],
  ["m-plus-1-code-117-wght-normal.woff2", mPlus_m_plus_1_code_117_wght_normal_woff2],
  ["m-plus-1-code-118-wght-normal.woff2", mPlus_m_plus_1_code_118_wght_normal_woff2],
  ["m-plus-1-code-119-wght-normal.woff2", mPlus_m_plus_1_code_119_wght_normal_woff2],
  ["m-plus-1-code-12-wght-normal.woff2", mPlus_m_plus_1_code_12_wght_normal_woff2],
  ["m-plus-1-code-13-wght-normal.woff2", mPlus_m_plus_1_code_13_wght_normal_woff2],
  ["m-plus-1-code-14-wght-normal.woff2", mPlus_m_plus_1_code_14_wght_normal_woff2],
  ["m-plus-1-code-15-wght-normal.woff2", mPlus_m_plus_1_code_15_wght_normal_woff2],
  ["m-plus-1-code-16-wght-normal.woff2", mPlus_m_plus_1_code_16_wght_normal_woff2],
  ["m-plus-1-code-17-wght-normal.woff2", mPlus_m_plus_1_code_17_wght_normal_woff2],
  ["m-plus-1-code-18-wght-normal.woff2", mPlus_m_plus_1_code_18_wght_normal_woff2],
  ["m-plus-1-code-19-wght-normal.woff2", mPlus_m_plus_1_code_19_wght_normal_woff2],
  ["m-plus-1-code-20-wght-normal.woff2", mPlus_m_plus_1_code_20_wght_normal_woff2],
  ["m-plus-1-code-21-wght-normal.woff2", mPlus_m_plus_1_code_21_wght_normal_woff2],
  ["m-plus-1-code-22-wght-normal.woff2", mPlus_m_plus_1_code_22_wght_normal_woff2],
  ["m-plus-1-code-23-wght-normal.woff2", mPlus_m_plus_1_code_23_wght_normal_woff2],
  ["m-plus-1-code-24-wght-normal.woff2", mPlus_m_plus_1_code_24_wght_normal_woff2],
  ["m-plus-1-code-25-wght-normal.woff2", mPlus_m_plus_1_code_25_wght_normal_woff2],
  ["m-plus-1-code-26-wght-normal.woff2", mPlus_m_plus_1_code_26_wght_normal_woff2],
  ["m-plus-1-code-27-wght-normal.woff2", mPlus_m_plus_1_code_27_wght_normal_woff2],
  ["m-plus-1-code-28-wght-normal.woff2", mPlus_m_plus_1_code_28_wght_normal_woff2],
  ["m-plus-1-code-29-wght-normal.woff2", mPlus_m_plus_1_code_29_wght_normal_woff2],
  ["m-plus-1-code-3-wght-normal.woff2", mPlus_m_plus_1_code_3_wght_normal_woff2],
  ["m-plus-1-code-30-wght-normal.woff2", mPlus_m_plus_1_code_30_wght_normal_woff2],
  ["m-plus-1-code-31-wght-normal.woff2", mPlus_m_plus_1_code_31_wght_normal_woff2],
  ["m-plus-1-code-32-wght-normal.woff2", mPlus_m_plus_1_code_32_wght_normal_woff2],
  ["m-plus-1-code-33-wght-normal.woff2", mPlus_m_plus_1_code_33_wght_normal_woff2],
  ["m-plus-1-code-34-wght-normal.woff2", mPlus_m_plus_1_code_34_wght_normal_woff2],
  ["m-plus-1-code-35-wght-normal.woff2", mPlus_m_plus_1_code_35_wght_normal_woff2],
  ["m-plus-1-code-36-wght-normal.woff2", mPlus_m_plus_1_code_36_wght_normal_woff2],
  ["m-plus-1-code-37-wght-normal.woff2", mPlus_m_plus_1_code_37_wght_normal_woff2],
  ["m-plus-1-code-38-wght-normal.woff2", mPlus_m_plus_1_code_38_wght_normal_woff2],
  ["m-plus-1-code-39-wght-normal.woff2", mPlus_m_plus_1_code_39_wght_normal_woff2],
  ["m-plus-1-code-40-wght-normal.woff2", mPlus_m_plus_1_code_40_wght_normal_woff2],
  ["m-plus-1-code-41-wght-normal.woff2", mPlus_m_plus_1_code_41_wght_normal_woff2],
  ["m-plus-1-code-42-wght-normal.woff2", mPlus_m_plus_1_code_42_wght_normal_woff2],
  ["m-plus-1-code-43-wght-normal.woff2", mPlus_m_plus_1_code_43_wght_normal_woff2],
  ["m-plus-1-code-44-wght-normal.woff2", mPlus_m_plus_1_code_44_wght_normal_woff2],
  ["m-plus-1-code-45-wght-normal.woff2", mPlus_m_plus_1_code_45_wght_normal_woff2],
  ["m-plus-1-code-46-wght-normal.woff2", mPlus_m_plus_1_code_46_wght_normal_woff2],
  ["m-plus-1-code-47-wght-normal.woff2", mPlus_m_plus_1_code_47_wght_normal_woff2],
  ["m-plus-1-code-48-wght-normal.woff2", mPlus_m_plus_1_code_48_wght_normal_woff2],
  ["m-plus-1-code-49-wght-normal.woff2", mPlus_m_plus_1_code_49_wght_normal_woff2],
  ["m-plus-1-code-5-wght-normal.woff2", mPlus_m_plus_1_code_5_wght_normal_woff2],
  ["m-plus-1-code-50-wght-normal.woff2", mPlus_m_plus_1_code_50_wght_normal_woff2],
  ["m-plus-1-code-53-wght-normal.woff2", mPlus_m_plus_1_code_53_wght_normal_woff2],
  ["m-plus-1-code-54-wght-normal.woff2", mPlus_m_plus_1_code_54_wght_normal_woff2],
  ["m-plus-1-code-55-wght-normal.woff2", mPlus_m_plus_1_code_55_wght_normal_woff2],
  ["m-plus-1-code-56-wght-normal.woff2", mPlus_m_plus_1_code_56_wght_normal_woff2],
  ["m-plus-1-code-58-wght-normal.woff2", mPlus_m_plus_1_code_58_wght_normal_woff2],
  ["m-plus-1-code-59-wght-normal.woff2", mPlus_m_plus_1_code_59_wght_normal_woff2],
  ["m-plus-1-code-6-wght-normal.woff2", mPlus_m_plus_1_code_6_wght_normal_woff2],
  ["m-plus-1-code-60-wght-normal.woff2", mPlus_m_plus_1_code_60_wght_normal_woff2],
  ["m-plus-1-code-61-wght-normal.woff2", mPlus_m_plus_1_code_61_wght_normal_woff2],
  ["m-plus-1-code-62-wght-normal.woff2", mPlus_m_plus_1_code_62_wght_normal_woff2],
  ["m-plus-1-code-63-wght-normal.woff2", mPlus_m_plus_1_code_63_wght_normal_woff2],
  ["m-plus-1-code-64-wght-normal.woff2", mPlus_m_plus_1_code_64_wght_normal_woff2],
  ["m-plus-1-code-65-wght-normal.woff2", mPlus_m_plus_1_code_65_wght_normal_woff2],
  ["m-plus-1-code-66-wght-normal.woff2", mPlus_m_plus_1_code_66_wght_normal_woff2],
  ["m-plus-1-code-67-wght-normal.woff2", mPlus_m_plus_1_code_67_wght_normal_woff2],
  ["m-plus-1-code-68-wght-normal.woff2", mPlus_m_plus_1_code_68_wght_normal_woff2],
  ["m-plus-1-code-69-wght-normal.woff2", mPlus_m_plus_1_code_69_wght_normal_woff2],
  ["m-plus-1-code-7-wght-normal.woff2", mPlus_m_plus_1_code_7_wght_normal_woff2],
  ["m-plus-1-code-70-wght-normal.woff2", mPlus_m_plus_1_code_70_wght_normal_woff2],
  ["m-plus-1-code-71-wght-normal.woff2", mPlus_m_plus_1_code_71_wght_normal_woff2],
  ["m-plus-1-code-72-wght-normal.woff2", mPlus_m_plus_1_code_72_wght_normal_woff2],
  ["m-plus-1-code-73-wght-normal.woff2", mPlus_m_plus_1_code_73_wght_normal_woff2],
  ["m-plus-1-code-74-wght-normal.woff2", mPlus_m_plus_1_code_74_wght_normal_woff2],
  ["m-plus-1-code-75-wght-normal.woff2", mPlus_m_plus_1_code_75_wght_normal_woff2],
  ["m-plus-1-code-76-wght-normal.woff2", mPlus_m_plus_1_code_76_wght_normal_woff2],
  ["m-plus-1-code-77-wght-normal.woff2", mPlus_m_plus_1_code_77_wght_normal_woff2],
  ["m-plus-1-code-78-wght-normal.woff2", mPlus_m_plus_1_code_78_wght_normal_woff2],
  ["m-plus-1-code-79-wght-normal.woff2", mPlus_m_plus_1_code_79_wght_normal_woff2],
  ["m-plus-1-code-8-wght-normal.woff2", mPlus_m_plus_1_code_8_wght_normal_woff2],
  ["m-plus-1-code-80-wght-normal.woff2", mPlus_m_plus_1_code_80_wght_normal_woff2],
  ["m-plus-1-code-81-wght-normal.woff2", mPlus_m_plus_1_code_81_wght_normal_woff2],
  ["m-plus-1-code-82-wght-normal.woff2", mPlus_m_plus_1_code_82_wght_normal_woff2],
  ["m-plus-1-code-83-wght-normal.woff2", mPlus_m_plus_1_code_83_wght_normal_woff2],
  ["m-plus-1-code-84-wght-normal.woff2", mPlus_m_plus_1_code_84_wght_normal_woff2],
  ["m-plus-1-code-85-wght-normal.woff2", mPlus_m_plus_1_code_85_wght_normal_woff2],
  ["m-plus-1-code-86-wght-normal.woff2", mPlus_m_plus_1_code_86_wght_normal_woff2],
  ["m-plus-1-code-87-wght-normal.woff2", mPlus_m_plus_1_code_87_wght_normal_woff2],
  ["m-plus-1-code-88-wght-normal.woff2", mPlus_m_plus_1_code_88_wght_normal_woff2],
  ["m-plus-1-code-89-wght-normal.woff2", mPlus_m_plus_1_code_89_wght_normal_woff2],
  ["m-plus-1-code-9-wght-normal.woff2", mPlus_m_plus_1_code_9_wght_normal_woff2],
  ["m-plus-1-code-90-wght-normal.woff2", mPlus_m_plus_1_code_90_wght_normal_woff2],
  ["m-plus-1-code-91-wght-normal.woff2", mPlus_m_plus_1_code_91_wght_normal_woff2],
  ["m-plus-1-code-92-wght-normal.woff2", mPlus_m_plus_1_code_92_wght_normal_woff2],
  ["m-plus-1-code-93-wght-normal.woff2", mPlus_m_plus_1_code_93_wght_normal_woff2],
  ["m-plus-1-code-94-wght-normal.woff2", mPlus_m_plus_1_code_94_wght_normal_woff2],
  ["m-plus-1-code-95-wght-normal.woff2", mPlus_m_plus_1_code_95_wght_normal_woff2],
  ["m-plus-1-code-96-wght-normal.woff2", mPlus_m_plus_1_code_96_wght_normal_woff2],
  ["m-plus-1-code-97-wght-normal.woff2", mPlus_m_plus_1_code_97_wght_normal_woff2],
  ["m-plus-1-code-98-wght-normal.woff2", mPlus_m_plus_1_code_98_wght_normal_woff2],
  ["m-plus-1-code-99-wght-normal.woff2", mPlus_m_plus_1_code_99_wght_normal_woff2],
  ["m-plus-1-code-latin-ext-wght-normal.woff2", mPlus_m_plus_1_code_latin_ext_wght_normal_woff2],
  ["m-plus-1-code-latin-wght-normal.woff2", mPlus_m_plus_1_code_latin_wght_normal_woff2],
  ["m-plus-1-code-vietnamese-wght-normal.woff2", mPlus_m_plus_1_code_vietnamese_wght_normal_woff2],
]);
