import { relative } from "node:path";
import { fileURLToPath } from "node:url";
// @ts-expect-error -- Bun resolves this CSS file as plain text at runtime
import mPlusCss from "@fontsource-variable/m-plus-1-code/index.css" with { type: "text" };

const OUTPUT_FILE = fileURLToPath(new URL("../server/m-plus-font-files.ts", import.meta.url));
const SOURCE_PACKAGE = "@fontsource-variable/m-plus-1-code";
const GENERATOR_SCRIPT = "scripts/generate-m-plus-font-files.ts";

interface FontEntry {
  filename: string;
  identifier: string;
}

function collectFontFilenames(cssText: string): string[] {
  const filenames = new Set<string>();
  for (const match of cssText.matchAll(/url\(\.\/files\/([^)]+)\)/g)) {
    filenames.add(match[1] as string);
  }

  return [...filenames].sort((a, b) => a.localeCompare(b));
}

function toIdentifier(filename: string): string {
  const normalized = filename.replaceAll(/[^A-Za-z0-9]+/g, "_").replaceAll(/^_+|_+$/g, "");
  return `mPlus_${normalized}`;
}

function buildEntries(filenames: string[]): FontEntry[] {
  const entries = filenames.map((filename) => ({ filename, identifier: toIdentifier(filename) }));
  const seen = new Set<string>();

  for (const entry of entries) {
    if (seen.has(entry.identifier)) {
      throw new Error(`Identifier collision detected for ${entry.identifier}`);
    }
    seen.add(entry.identifier);
  }

  return entries;
}

function renderFile(entries: FontEntry[]): string {
  const lines: string[] = [];
  lines.push(`// Auto-generated by ${GENERATOR_SCRIPT}`);
  lines.push("// Do not edit manually.");
  lines.push("// biome-ignore-all assist/source/organizeImports: generated file");
  lines.push("");

  for (const entry of entries) {
    lines.push("// @ts-expect-error -- Bun resolves this font to an embedded asset path at compile time");
    lines.push(`import ${entry.identifier} from "${SOURCE_PACKAGE}/files/${entry.filename}" with {`);
    lines.push('  type: "file",');
    lines.push("};");
  }

  lines.push("");
  lines.push("export const mPlusFontFiles = new Map<string, string>([");
  for (const entry of entries) {
    lines.push(`  ["${entry.filename}", ${entry.identifier}],`);
  }
  lines.push("]);");

  return `${lines.join("\n")}\n`;
}

function failStale() {
  const path = relative(process.cwd(), OUTPUT_FILE);
  console.error(`Generated file is stale: ${path}`);
  console.error("Run: bun run gen:m-plus-font-files");
  process.exit(1);
}

async function main(): Promise<void> {
  const checkOnly = process.argv.includes("--check");
  const entries = buildEntries(collectFontFilenames(mPlusCss));
  const nextContent = renderFile(entries);

  const output = Bun.file(OUTPUT_FILE);
  const exists = await output.exists();
  if (!exists) {
    if (checkOnly) failStale();
    await Bun.write(OUTPUT_FILE, nextContent);
    console.log(`Generated ${relative(process.cwd(), OUTPUT_FILE)} (${entries.length} files)`);
    return;
  }

  const currentContent = await output.text();
  if (currentContent !== nextContent) {
    if (checkOnly) failStale();
    await Bun.write(OUTPUT_FILE, nextContent);
    console.log(`Updated ${relative(process.cwd(), OUTPUT_FILE)} (${entries.length} files)`);
    return;
  }

  if (!checkOnly) {
    console.log(`No changes: ${relative(process.cwd(), OUTPUT_FILE)} (${entries.length} files)`);
  }
}

await main();
